_id: 61d562a78d6d5d002effa0e9
title: Ship
description: Ships
icon: view_stream
primary: title
readOnly: false
history: false
properties:
  title:
    type: string
    title: title
    description: Title of the row
    options:
      position: left
  description:
    type: textarea
    title: description
    description: Description of the row
    options:
      position: left
  storage:
    type: number
    title: storage
    description: Description of the storage input
    options:
      position: right
    minimum: 0
    default: 0
  speed:
    type: number
    title: speed
    description: Description of the speed input
    options:
      position: right
    minimum: 0
    default: 0
acl:
  write: true==true
  read: true==true
order: 12
