_id: 61d562a58d6d5d002effa0e3
title: Agreements
description: Agreements
icon: view_stream
primary: title
readOnly: false
history: false
properties:
  title:
    type: string
    title: title
    description: Title of the row
    options:
      position: left
  description:
    type: textarea
    title: description
    description: Description of the row
    options:
      position: left
  product:
    type: relation
    title: product
    description: Description of the product input
    options:
      position: right
    relationType: onetoone
    dependent: false
    primary: title
    bucketId: 61d5629f8d6d5d002effa0d7
  contracted_country:
    type: relation
    title: contracted_country
    description: Description of the contracted_country input
    options:
      position: right
    relationType: onetoone
    dependent: false
    primary: title
    bucketId: 61d5629d8d6d5d002effa0d1
  contracting_country:
    type: relation
    title: contracting_country
    description: Description of the contracting_country input
    options:
      position: right
    relationType: onetoone
    dependent: false
    primary: title
    bucketId: 61d5629d8d6d5d002effa0d1
  agreement_rating:
    type: number
    title: agreement_rating
    description: Description of the agreement_rating input
    options:
      position: right
    minimum: 0
    default: 0
  in_agreement:
    type: boolean
    title: in_agreement
    description: Description of the in_agreement input
    options:
      position: bottom
    default: true
acl:
  write: true==true
  read: true==true
order: 10
