_id: 61d5629e8d6d5d002effa0d4
title: City
description: Cities
icon: view_stream
primary: title
readOnly: false
history: false
properties:
  title:
    type: string
    title: title
    description: Title of the row
    options:
      position: left
  country:
    type: relation
    title: country
    description: Description of the country input
    options:
      position: left
    relationType: onetoone
    dependent: false
    primary: title
    bucketId: 61d5629d8d6d5d002effa0d1
  population:
    type: number
    title: population
    description: Description of the population input
    options:
      position: right
    minimum: 0
    default: 0
acl:
  write: true==true
  read: true==true
order: 5
