_id: 61d562a98d6d5d002effa0ec
title: News
description: News About Everything
icon: view_stream
primary: title
readOnly: false
history: false
properties:
  title:
    type: string
    title: title
    description: Title of the row
    options:
      position: left
  description:
    type: textarea
    title: description
    description: Description of the row
    options:
      position: left
  subject:
    type: string
    title: subject
    description: Description of the subject input
    options:
      position: right
    enum:
      - topic
      - war
      - embargo
      - agreement
    default: topic
  for_subscribers:
    type: boolean
    title: for_subscribers
    description: Description of the for_subscribers input
    options:
      position: right
    default: false
acl:
  write: true==true
  read: true==true
order: 13
