_id: 61d562a68d6d5d002effa0e6
title: Embargos
description: Embargos
icon: view_stream
primary: title
readOnly: false
history: false
properties:
  title:
    type: string
    title: title
    description: Title of the row
    options:
      position: left
  description:
    type: textarea
    title: description
    description: Description of the row
    options:
      position: left
  embargoed_country:
    type: relation
    title: embargoed_country
    description: Description of the embargoed_country input
    options:
      position: right
    relationType: onetoone
    dependent: false
    bucketId: 61d5629d8d6d5d002effa0d1
  embargoing_country:
    type: relation
    title: embargoing_country
    description: Description of the embargoing_country input
    options:
      position: right
    relationType: onetoone
    dependent: false
    bucketId: 61d5629d8d6d5d002effa0d1
  products:
    type: relation
    title: products
    description: Description of the products input
    options:
      position: left
    relationType: onetomany
    dependent: false
    bucketId: 61d5629f8d6d5d002effa0d7
  deleted_product_rate:
    type: number
    title: deleted_product_rate
    description: Description of the deleted_product_rate input
    options:
      position: right
    minimum: 0
    default: 0
  consumption_rate_decrease:
    type: number
    title: consumption_rate_decrease
    description: Description of the consumption_rate_decrease input
    options:
      position: right
    minimum: 0
    default: 0
  in_embargo:
    type: boolean
    title: in_embargo
    description: Description of the in_embargo input
    options:
      position: bottom
    default: true
acl:
  write: true==true
  read: true==true
order: 11
