_id: 61e562230cffb9002d35cabe
title: Test Index
description: Describe your new bucket
icon: view_stream
primary: title
readOnly: false
history: false
properties:
  title:
    type: string
    title: title
    description: Title of the row
    options:
      position: left
  description:
    type: textarea
    title: description
    description: Description of the row
    options:
      position: right
  count:
    type: number
    title: count
    description: Description of the count input
    options:
      position: bottom
      index: false
  user:
    type: string
    title: user
    description: Description of the user input
    options:
      position: bottom
      index: false
  point:
    type: string
    title: point
    description: Description of the point input
    options:
      position: bottom
      index: true
  img:
    type: storage
    title: img
    description: Description of the img input
    options:
      position: bottom
acl:
  write: true==true
  read: true==true
order: 0
